INSERT INTO YARN(YARNID, NAME, SKEINLENGTH, COLOR, PRICE) VALUES('1', 'Cherry Blossom', 425.0, 'RED', 35.99);
INSERT INTO YARN(YARNID, NAME, SKEINLENGTH, COLOR, PRICE) VALUES('2', 'Mountain Jewel', 825.0, 'PURPLE', 40.99);
INSERT INTO YARN(YARNID, NAME, SKEINLENGTH, COLOR, PRICE) VALUES('3', 'Terra Cotta', 210.0, 'ORANGE', 16.99);
INSERT INTO YARN(YARNID, NAME, SKEINLENGTH, COLOR, PRICE) VALUES('4', 'Smokestack', 425.0, 'GREY', 32.99);

INSERT INTO NEEDLES(NEEDLEID, NEEDLETYPE, MATERIAL, SIZE) VALUES('1', 'DPN', 'WOOD', 10.5);
INSERT INTO NEEDLES(NEEDLEID, NEEDLETYPE, MATERIAL, SIZE) VALUES('2', 'CIRCULAR', 'WOOD', 1);
INSERT INTO NEEDLES(NEEDLEID, NEEDLETYPE, MATERIAL, SIZE) VALUES('3', 'DPN', 'METAL', 3);
INSERT INTO NEEDLES(NEEDLEID, NEEDLETYPE, MATERIAL, SIZE) VALUES('4', 'STRAIGHT', 'WOOD', 5);
INSERT INTO NEEDLES(NEEDLEID, NEEDLETYPE, MATERIAL, SIZE) VALUES('5', 'CIRCULAR', 'WOOD', 15);
INSERT INTO NEEDLES(NEEDLEID, NEEDLETYPE, MATERIAL, SIZE) VALUES('6', 'DPN', 'BAMBOO', 17);
INSERT INTO NEEDLES(NEEDLEID, NEEDLETYPE, MATERIAL, SIZE) VALUES('7', 'DPN', 'WOOD', 11);
INSERT INTO NEEDLES(NEEDLEID, NEEDLETYPE, MATERIAL, SIZE) VALUES('8', 'DPN', 'WOOD', 13);
INSERT INTO NEEDLES(NEEDLEID, NEEDLETYPE, MATERIAL, SIZE) VALUES('9', 'CIRCULAR', 'WOOD', 2);
